name: build and push
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build with Gradle
        run: ./gradlew jib
      -
        name: Pull Trigger
        run: |
            curl -X POST ${{secrets.DOCKER_PULL_TRIGGER_URL}} \
            --data image=${{secrets.DOCKER_IMAGE}} \
            --data port=8081 \
            --data targetPort=3000
